[manifest]
version = "1.0.0"
dump_lua = true
priority = -999999999

# parse_string prep
[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = '''
      local str_parts, str_it = {}, 1
'''
position = 'after'
match_indent = false
payload = '''
    local function save_string(override)
        if override or str_parts[1] and str_parts[1] ~= ' ' then
            parsed_line[#parsed_line+1] = {strings = str_parts, control = copy_table(control) or {}}
        end
        str_parts, str_it = {}, 1
    end
'''

# line separator
[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = '''
      elseif not _c and char ~= '#' and not _s_gather then str_parts[str_it] = (str_parts[str_it] or '')..(control['X'] and char:gsub("%s+", "") or char)
'''
position = 'before'
match_indent = false
payload = '''
    elseif not _c and char == ' ' then
    save_string(false)
    local old_bg = control['X']
    control['X'] = nil
    str_parts = {' '}
    save_string(true)
    control['X'] = old_bg
'''

# force function
[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = '''
if str_parts[1] then parsed_line[#parsed_line+1] = {strings = str_parts, control = control or {}} end
'''
position = 'at'
match_indent = false
payload = '''
    if str_parts[1] then save_string(false) end
'''

# loc acc
# desc
[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = '''
for _, line in ipairs(center.text) do
'''
position = 'before'
match_indent = false
payload = '''
    G.Icons_temp_loc_acc = 1
    G.Icons_temp_loc_process = true
'''

[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = '''
center.name_parsed = {}
'''
position = 'after'
match_indent = false
payload = '''
    G.Icons_temp_loc_acc = nil
    G.Icons_temp_loc_process = nil
'''

# name
[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = '''
if center.unlock then
'''
position = 'after'
match_indent = false
payload = '''
    G.Icons_temp_loc_acc = nil
'''

# weird blind thing
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''local _reward = true'''
position = 'before'
match_indent = false
payload = '''
    local target = target or {vars = {}}
    target.vars = target.vars or {}
    target.vars.elements = target.vars.elements or {}
    for _,v in ipairs(Icons.get_needed_icons(target)) do
            table.insert(
            target.vars.elements,
            { n=G.UIT.C, config = { align="cm" }, nodes = { 
                { n=G.UIT.O, config= { object =
                    SMODS.create_sprite(0, 0, 0.3, 0.3, v.atlas or 'ico_icons', v.pos or {x = 0, y = 0})
                } }
            } }
        )
    end
'''

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''if discovered then'''
position = 'before'
match_indent = false
payload = '''
    local target = target or {vars = {}}
    target.vars = target.vars or {}
    target.vars.elements = target.vars.elements or {}
    for _,v in ipairs(Icons.get_needed_icons(target)) do
            table.insert(
            target.vars.elements,
            { n=G.UIT.C, config = { align="cm" }, nodes = { 
                { n=G.UIT.O, config= { object =
                    SMODS.create_sprite(0, 0, 0.3, 0.3, v.atlas or 'ico_icons', v.pos or {x = 0, y = 0})
                } }
            } }
        )
    end
'''